---
name: Scheduled Deploy From Main to Staging
on:
  # schedule:
  #   - cron: '0 10 * * 1-5'
  # Disable Schedule for Pen Testing
  workflow_dispatch: null
jobs:
  trivy-scan:
    uses: ./.github/workflows/security/trivy.yml
    secrets: inherit
    permissions:
      contents: read
      packages: write
      actions: read
      security-events: write

  build-container:
    needs:
      - trivy-scan
    uses: ./.github/workflows/docker/build-docker-container.yml
    secrets: inherit
    permissions:
      contents: read
      packages: write
    with:
      docker-name: fac
      image-name: web-container
      repo-name: gsa-tts/fac
      work-dir: ./backend

  testing:
    name: Run Django, Lighthouse, a11y and lint
    needs:
      - build-container
    uses: ./.github/workflows/testing/testing-from-ghcr.yml
    secrets: inherit

  linting:
    uses: ./.github/workflows/linting/linting.yml
    secrets: inherit

  create-pr:
    needs:
      - testing
    name: Create Pull Request to Staging
    uses: ./.github/workflows/deployments/create-pull-request.yml
    secrets: inherit
