---
applications:
  - name: ((app_name))
    buildpacks:
      - python_buildpack
    memory: ((mem_amount))
    path: ../
    timeout: 180
    env:
      ENV: ((cf_env_name))
      DJANGO_BASE_URL: https://fac-((env_name)).app.cloud.gov
      ALLOWED_HOSTS: fac-((env_name)).app.cloud.gov
      AV_SCAN_URL: https://fac-av-((service_name)).apps.internal:61443/scan
      # DISABLE_COLLECTSTATIC: true
    routes:
      - route: fac-((env_name)).app.cloud.gov
    instances: ((instances))
    services:
      - fac-db
      - fac-public-s3
      - fac-key-service
      - newrelic-creds
      - https-proxy-creds
