---
name: Build and Publish Docker Container
on:
  workflow_dispatch:
    inputs:
      docker-name:
        required: true
        type: string
        default: fac
      image-name:
        required: true
        type: string
        default: web-container
      repo-name:
        required: true
        type: string
        default: gsa-tts/fac
      work-dir:
        required: true
        type: string
        default: ./backend
  workflow_call:
    inputs:
      docker-name:
        required: true
        type: string
        default: fac
      image-name:
        required: true
        type: string
        default: web-container
      repo-name:
        required: true
        type: string
        default: gsa-tts/fac
      work-dir:
        required: true
        type: string
        default: ./backend

env:
  DOCKER_NAME: ${{ inputs.docker-name }}
  IMAGE: ${{ inputs.image-name }}
  GH_REPO: ${{ inputs.repo-name }}
  WORKING_DIRECTORY: ${{ inputs.work-dir }}

jobs:
  build-with-docker:
    name: Build Docker Container
    runs-on: ubuntu-latest
    permissions:
        contents: read
        packages: write
    steps:
      - name: Get Date
        shell: bash
        id: date
        run: echo "date=$(date +%Y%m%d)" >> $GITHUB_OUTPUT

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Create ssl key file
        working-directory: ${{ env.WORKING_DIRECTORY }}
        shell: bash
        env:
          SSL_KEY: ${{ secrets.RSA_KEY }}
        run: |
          echo "$SSL_KEY" > private.pem
          chmod 600 private.pem
          openssl rsa -in "private.pem" -pubout > "public.pem"

      - name: Add signer
        working-directory: ${{ env.WORKING_DIRECTORY }}
        shell: bash
        run: |
          docker trust signer add --key "public.pem" "${{ inputs.docker-name }}-team" "${{ env.GH_REPO }}/${{ env.IMAGE }}"

      - name: Load the private key onto Docker trust store
        working-directory: ${{ env.WORKING_DIRECTORY }}
        shell: bash
        run: |
          docker trust key load --name "fac-codesign" "private.pem"
          GREEN='\033[0;32m'
          PURPLE='\033[0;35m'
          NC='\033[0m' # No Color
          echo -e "Confirm \"${GREEN}Successfully imported key from private.pem${NC}\"" \
          "\nIf successful, IGNORE  \"${PURPLE}failed to import key to store: ...${NC}\" (due to unused content within private key)"

      - name: Build Container
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: docker build -t ${{ env.DOCKER_NAME }}:${{ steps.date.outputs.date }} .

      - name: Tag Image
        run: docker tag ${{ env.DOCKER_NAME }}:${{ steps.date.outputs.date }} ghcr.io/${{ env.GH_REPO }}/${{ env.IMAGE }}:latest

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Web Container
        run: docker push --all-tags ghcr.io/${{ env.GH_REPO }}/${{ env.IMAGE }} --disable-content-trust=false
