name: Deploy to the staging cloud.gov environment
on:
  push:
    branches:
      - prod

jobs:
  # testing
  test-and-lint:
    uses: ./.github/workflows/test-and-lint-from-ghcr.yml
    secrets: inherit

  # deploy to staging
  scan-dev:
    name: Zap scan of the dev site
    uses: ./.github/workflows/zap-scan.yml
    with:
      url: "https://fac-dev.app.cloud.gov/"

  deploy-infrastructure-staging:
    name: Deploy infrastructure (staging)
    needs:
      - test-and-lint
      - scan-dev
    uses: ./.github/workflows/terraform-apply-env.yml
    with:
      environment: "staging"
    secrets: inherit

  deploy-staging:
    name: Deploy staging app to cloud.gov
    needs:
      - deploy-infrastructure-staging
    uses: ./.github/workflows/deploy-apps.yml
    with:
      environment: "staging"
    secrets: inherit
