name: Django Migration Integrity Check

permissions:
  pull-requests: read

on:
  pull_request:
    paths:
      - 'backend/dissemination/models/**'
      - 'backend/dissemination/migrations/**'
      - 'requirements.txt' # Run if dependencies change too

jobs:
  validate-migrations:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' # This should match our project version

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Migration Check
        env:
          DJANGO_SETTINGS_MODULE: settings.py
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: |
          # --check: Exits with a non-zero status if migrations are missing
          # --dry-run: Doesn't actually create the files
          python backend/manage.py makemigrations --check --dry-run dissemination
